services:
  colmap:
    image: colmap/colmap:latest
    volumes:
      - ./data:/code/data
    working_dir: /working
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: colmap automatic_reconstructor --image_path ./images/ --workspace_path .   
  opensplat:
    build: .
    volumes:
      - ./data:/code/data
      - ./result:/code/result
    tty: true
    stdin_open: true
    depends_on:
      - colmap
    entrypoint: |
      /bin/bash -c "
      while [ ! -f /code/data/dense/0/fused.ply ]; do sleep 1; done;
      ./build/opensplat /code/data/ -n 2000 && mv /code/data/splat.py /code/result/
      "