services:
  colmap:
    image: colmap/colmap:latest
    volumes:
      - ./data:/code/data
    working_dir: /code
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: colmap automatic_reconstructor --image_path ./data/images/ --workspace_path ./data/
  opensplat:
    build: .
    volumes:
      - ./data:/code/data
      - ./result:/code/result
    tty: true
    stdin_open: true
    depends_on:
      - colmap
    entrypoint: |
      /bin/bash -c "
      while [ ! -f /code/data/dense/0/fused.ply ]; do sleep 1; done;
      ./build/opensplat /code/data/ -n 2000 && mv splat.ply result/
      "